Parameters:
  LambdaArn:
    Type: String
    Default: arn:aws:lambda:ap-northeast-1:956228753252:function:dynamdbtest
Resources:
  ScheduledEvent:
    Type: 'AWS::Events::Rule'
    Properties:
      Description: 'Scheduled event to disable accounts'
      ScheduleExpression: 'cron(0 0 * * ? *)'
      Targets:
        - Arn: !Ref LambdaArn
          Id: 'TargetFunctionV1'